version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: obras_backend
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      FRONTEND_URL: "https://obras.solkbd.com"
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - obras_network

  frontend:
    image: nginx:alpine
    container_name: obras_frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    networks:
      - obras_network

networks:
  obras_network:
    driver: bridge
